from datetime import datetime
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


class Flats(db.Model):
    __tablename__ = 'property'
    id = db.Column(db.Integer, primary_key=True)
    price = db.Column(db.Float, nullable=False)
    rooms = db.Column(db.Integer,nullable=True)
    area = db.Column(db.Float, nullable=False)
    own = db.Column(db.String(100), nullable=False)
    year_of_building = db.Column(db.String(100), nullable=True)
    available = db.Column(db.DateTime, nullable=True)
    rent = db.Column(db.Integer, nullable=True)
    floor = db.Column(db.String(100), nullable=True)
    heating = db.Column(db.String(100), nullable=True)
    car_park = db.Column(db.String(100), nullable=True)
    market = db.Column(db.String(100), nullable=True)
    advertiser_add = db.Column(db.String(100), nullable=True)
    state_of_the_building_finish = db.Column(db.String(100), nullable=True)
    city = db.Column(db.String(100), nullable=False)
    province = db.Column(db.String(100), nullable=True)
    district = db.Column(db.String(100), nullable=True)
    street = db.Column(db.String(100), nullable=True)
    date_addition_add = db.Column(db.DateTime, nullable=True)
    date_actualisation_add = db.Column(db.DateTime, nullable=True)
    date_add_to_database = db.Column(db.DateTime, default=datetime.utcnow)
    type_of_building = db.Column(db.String(100), nullable=True)
    kind_of_investment = db.Column(db.String(100), nullable=True)
    building_material = db.Column(db.String(100), nullable=True)
    suplementary = db.Column(db.String(100), nullable=True)
    remote_service = db.Column(db.String(100), nullable=True)
    security = db.Column(db.String(100), nullable=True)
    media = db.Column(db.String(100), nullable=True)
    balcony = db.Column(db.String(100), nullable=True)
    windows = db.Column(db.String(100), nullable=True)
    elevator = db.Column(db.String(100), nullable=True)
    equipment = db.Column(db.String(100), nullable=True)
    nr_offert = db.Column(db.String(256), nullable=True)
    # contact_person  = db.Column(db.String(100), nullable=True)
    # contact_number = db.Column(db.String(100), nullable=True)
    link = db.Column(db.String(256), nullable=True)
